#!/usr/bin/env python3.6

adj_dict = {
    'AL': ('MS', 'TN', 'GA', 'FL'),
    'AZ': ('CA', 'NV', 'UT', 'NM'),
    'AR': ('MO', 'TN', 'MS', 'LA', 'TX', 'OK'),
    'CA': ('OR', 'NV', 'AZ'),
    'CO': ('WY', 'NE', 'KS', 'OK', 'NM', 'UT'),
    'CT': ('NY', 'MA', 'RI'),
    'DE': ('NJ', 'PA', 'MD'),
    'DC': ('MD', 'VA'),
    'FL': ('AL', 'GA'),
    'GA': ('TN', 'NC', 'SC', 'FL', 'AL'),
    'ID': ('WA', 'MT', 'WY', 'UT', 'NV', 'OR'),
    'IL': ('WI', 'IN', 'KY', 'MO', 'IA'),
    'IN': ('MI', 'OH', 'KY', 'IL'),
    'IA': ('MN', 'WI', 'IL', 'MO', 'NE', 'SD'),
    'KS': ('NE', 'MO', 'OK', 'CO'),
    'KY': ('IN', 'OH', 'WV', 'VA', 'TN', 'MO', 'IL'),
    'LA': ('AR', 'MS', 'TX'),
    'ME': ('NH',),
    'MD': ('PA', 'DE', 'DC', 'VA', 'WV'),
    'MA': ('NH', 'RI', 'CT', 'NY', 'VT'),
    'MI': ('OH', 'IN', 'WI'),
    'MN': ('WI', 'IA', 'SD', 'ND'),
    'MS': ('TN', 'AL', 'LA', 'AR'),
    'MO': ('NE', 'IA', 'IL', 'KY', 'TN', 'AR', 'OK', 'KS'),
    'MT': ('ND', 'SD', 'WY', 'ID'),
    'NE': ('SD', 'IA', 'MO', 'KS', 'CO', 'WY'),
    'NV': ('OR', 'ID', 'UT', 'AZ', 'CA'),
    'NH': ('ME', 'MA', 'VT'),
    'NJ': ('NY', 'DE', 'PA'),
    'NM': ('CO', 'OK', 'TX', 'AZ'),
    'NY': ('VT', 'MA', 'CT', 'NJ', 'PA'),
    'NC': ('VA', 'SC', 'GA', 'TN'),
    'ND': ('MN', 'SD', 'MT'),
    'OH': ('PA', 'WV', 'KY', 'IN', 'MI'),
    'OK': ('KS', 'MO', 'AR', 'TX', 'NM', 'CO'),
    'OR': ('WA', 'ID', 'NV', 'CA'),
    'PA': ('NY', 'NJ', 'DE', 'MD', 'WV', 'OH'),
    'RI': ('MA', 'CT'),
    'SC': ('NC', 'GA'),
    'SD': ('ND', 'MN', 'IA', 'NE', 'WY', 'MT'),
    'TN': ('KY', 'VA', 'NC', 'GA', 'AL', 'MS', 'AR', 'MO'),
    'TX': ('NM', 'OK', 'AR', 'LA'),
    'UT': ('ID', 'WY', 'CO', 'AZ', 'NV'),
    'VT': ('NH', 'MA', 'NY'),
    'VA': ('WV', 'MD', 'DC', 'NC', 'TN', 'KY'),
    'WA': ('ID', 'OR'),
    'WV': ('OH', 'PA', 'MD', 'VA', 'KY'),
    'WI': ('MI', 'IL', 'IA', 'MN'),
    'WY': ('MT', 'SD', 'NE', 'CO', 'UT', 'ID')
}